(() => {
  const repository = "https://github.com/AlexArceoDeveloper/portfolio";
  const projects = [
    { slug: "aspnet-core-api", number: "01", name: "ASP.NET Core API", focus: "A compact API reference implementation with explicit validation and integration tests.", focusEs: "Una implementación de referencia de API compacta con validación explícita y pruebas de integración.", stack: ["C#", "ASP.NET Core", "xUnit"], architecture: "A minimal API boundary keeps input validation, responses and integration behaviour easy to inspect.", architectureEs: "Un límite de API mínimo mantiene la validación de entrada, las respuestas y el comportamiento de integración fáciles de inspeccionar.", evidence: "Release build and xUnit API integration tests", evidenceEs: "Compilación Release y pruebas de integración de API con xUnit", source: "01-aspnet-core-api" },
    { slug: "ai-workflow-integration", number: "02", name: "AI Workflow Integration", focus: "A provider-neutral orchestration service with explicit tool boundaries and safe outputs.", focusEs: "Un servicio de orquestación neutral respecto al proveedor, con límites de herramientas explícitos y salidas seguras.", stack: [".NET", "REST APIs", "AI integration"], architecture: "The orchestration layer separates workflow intent from individual model-provider integrations.", architectureEs: "La capa de orquestación separa la intención del flujo de las integraciones concretas con proveedores de modelos.", evidence: "Release build in CI", evidenceEs: "Compilación Release en CI", source: "02-ai-workflow-integration" },
    { slug: "blazor-delivery-dashboard", number: "03", name: "Blazor Delivery Dashboard", focus: "A delivery-oriented Blazor interface that presents API-backed work clearly.", focusEs: "Una interfaz Blazor orientada a la entrega que presenta con claridad el trabajo respaldado por API.", stack: ["Blazor", "C#", "REST APIs"], architecture: "The UI consumes a defined application boundary and keeps operational status easy to understand.", architectureEs: "La interfaz consume un límite de aplicación definido y hace comprensible el estado operativo.", evidence: "Release build in CI", evidenceEs: "Compilación Release en CI", source: "03-blazor-delivery-dashboard" },
    { slug: "intelligent-commerce-platform", number: "04", name: "Intelligent Commerce Platform", focus: "A modern payments API with persistence, signed webhooks, idempotency and explainable risk rules.", focusEs: "Una API moderna de pagos con persistencia, webhooks firmados, idempotencia y reglas de riesgo explicables.", stack: [".NET 10", "EF Core", "PostgreSQL", "Docker"], architecture: "Domain rules, persistence and payment-facing boundaries are kept explicit for safe operational behaviour.", architectureEs: "Las reglas de dominio, la persistencia y los límites de pago se mantienen explícitos para un comportamiento operativo seguro.", evidence: "Executable domain tests, Compose and Kubernetes validation", evidenceEs: "Pruebas de dominio ejecutables y validación de Compose y Kubernetes", source: "04-intelligent-commerce-platform" },
    { slug: "agentic-knowledge-hub", number: "05", name: "Agentic Knowledge Hub", focus: "A grounded retrieval design with approval-aware agents, evaluation and external vector adapters.", focusEs: "Un diseño de recuperación fundamentada con agentes conscientes de aprobación, evaluación y adaptadores vectoriales externos.", stack: ["RAG", "Python", ".NET", "pgvector"], architecture: "Retrieval, evaluation and approval boundaries are independently testable rather than hidden inside a chat interface.", architectureEs: "Los límites de recuperación, evaluación y aprobación son comprobables de forma independiente, sin quedar ocultos en una interfaz de chat.", evidence: "Executable Python, safety, workflow and retrieval tests", evidenceEs: "Pruebas ejecutables de Python, seguridad, flujos y recuperación", source: "05-agentic-knowledge-hub" },
    { slug: "commerce-companion", number: "06", name: "Commerce Companion", focus: "A native .NET MAUI client that consumes the commerce API through typed, safe HTTP boundaries.", focusEs: "Un cliente nativo .NET MAUI que consume la API de comercio mediante límites HTTP tipados y seguros.", stack: [".NET MAUI", "C#", "MVVM"], architecture: "Client validation and API communication stay separated from the commerce service itself.", architectureEs: "La validación del cliente y la comunicación con la API permanecen separadas del propio servicio de comercio.", evidence: "Windows release build in CI", evidenceEs: "Compilación Release para Windows en CI", source: "06-commerce-companion" },
    { slug: "industrial-telemetry-platform", number: "07", name: "Industrial Telemetry Platform", focus: "A simulated industrial telemetry flow with MQTT ingestion, append-only events and an operations dashboard.", focusEs: "Un flujo simulado de telemetría industrial con ingesta MQTT, eventos de solo anexado y panel operativo.", stack: ["MQTT", "Blazor", "C#", "Docker"], architecture: "Telemetry ingestion, persistence and operations visibility are represented as distinct platform responsibilities.", architectureEs: "La ingesta de telemetría, la persistencia y la visibilidad operativa se representan como responsabilidades diferenciadas de plataforma.", evidence: "Executable rules and persistence tests", evidenceEs: "Reglas ejecutables y pruebas de persistencia", source: "07-industrial-telemetry-platform" },
    { slug: "ai-automation-backend", number: "08", name: "AI Automation Backend", focus: "A .NET 10 backend for agents, RAG, identity, observability and a Python neural-routing service.", focusEs: "Un backend .NET 10 para agentes, RAG, identidad, observabilidad y un servicio Python de enrutamiento neuronal.", stack: [".NET 10", "FastAPI", "OpenTelemetry", "PostgreSQL"], architecture: "The API, agent workflow, neural-routing service and operational telemetry are deliberately separated.", architectureEs: "La API, el flujo de agentes, el servicio de enrutamiento neuronal y la telemetría operativa están separados deliberadamente.", evidence: "Executable .NET and Python tests plus Compose topology", evidenceEs: "Pruebas ejecutables .NET y Python, además de topología Compose", source: "08-ai-automation-backend" },
    { slug: "ai-workflow-control-center", number: "09", name: "AI Workflow Control Center", focus: "An ASP.NET Core MVC control centre for explainable routing and approval-aware workflow planning.", focusEs: "Un centro de control ASP.NET Core MVC para enrutamiento explicable y planificación de flujos consciente de aprobaciones.", stack: ["ASP.NET Core MVC", "Razor", "C#"], architecture: "Strongly typed views make planning decisions and approval requirements visible to operators.", architectureEs: "Las vistas fuertemente tipadas hacen visibles para los operadores las decisiones de planificación y los requisitos de aprobación.", evidence: "Release build and executable planning tests", evidenceEs: "Compilación Release y pruebas ejecutables de planificación", source: "09-ai-workflow-control-center" },
    { slug: "field-assistant-blazor-hybrid", number: "10", name: "Field Assistant · Blazor Hybrid", focus: "A .NET MAUI Blazor Hybrid client with typed agent integration, HTTPS boundaries and an offline-safe outbox.", focusEs: "Un cliente .NET MAUI Blazor Hybrid con integración tipada de agentes, límites HTTPS y bandeja de salida segura sin conexión.", stack: [".NET MAUI", "Blazor Hybrid", "C#"], architecture: "Transient authentication, endpoint validation and offline handling are isolated in a reusable client core.", architectureEs: "La autenticación transitoria, la validación de endpoints y el manejo sin conexión se aíslan en un núcleo de cliente reutilizable.", evidence: "Windows release build and executable core tests", evidenceEs: "Compilación Release para Windows y pruebas ejecutables del núcleo", source: "10-field-assistant-blazor-hybrid" },
    { slug: "power-platform-service-requests", number: "11", name: "Power Platform Service Requests", focus: "An ALM-friendly request workflow design around Power Apps Canvas, SharePoint, Power Automate and Copilot Studio.", focusEs: "Un diseño de flujo de solicitudes compatible con ALM alrededor de Power Apps Canvas, SharePoint, Power Automate y Copilot Studio.", stack: ["Power Apps", "SharePoint", "Power Automate", "Copilot Studio"], architecture: "The Canvas app is the input boundary; SharePoint is the operational record; the flow validates, routes, records history and notifies owners.", architectureEs: "La aplicación Canvas es el límite de entrada; SharePoint, el registro operativo; y el flujo valida, enruta, registra historial y notifica a responsables.", evidence: "Offline schema and secret-safety validation", evidenceEs: "Validación sin conexión de esquemas y seguridad de secretos", source: "11-power-platform-service-requests", logo: "assets/service-requests-mark.svg" }
  ];

  const root = document.body.dataset.root || ".";
  const app = document.getElementById("app");
  const projectSlug = document.body.dataset.project;
  const escape = (value) => value.replace(/[&<>"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character]);
  const copy = {
    en: { projects: "Projects", source: "Source on GitHub", explore: "Explore project →", footer: "Personal engineering demonstrations. They are separate from professional employment experience and contain no employer-confidential information, credentials or production data.", heroTitle: "Engineering evidence, not just technology lists.", heroText: "Backend-focused software development, cloud-ready integrations and practical automation with the Microsoft stack. Each project links architecture decisions to runnable code, tests and deployment assets.", exploreProjects: "Explore projects", openRepository: "Open GitHub repository", selected: "Selected work", eleven: "Eleven focused demonstrators", selectedText: "Each page explains scope, architecture, relevant technology and the verification that supports the implementation.", principles: "Working principles", professional: "Professional by design", principlesText: "The portfolio favours clear boundaries, testable behaviour and deployable engineering evidence.", verifiable: "Verifiable", verifiableText: "Every increment is expected to build, test or validate through an appropriate local quality gate.", security: "Security-aware", securityText: "Projects avoid credentials, production data and hidden assumptions; integration boundaries are made explicit.", maintainable: "Maintainable", maintainableText: "Readable documentation, focused scope and clear architecture make each demonstration practical to explore.", viewSource: "View source and documentation", allProjects: "All projects", focus: "Focus", verification: "Verification", scope: "Scope", personal: "Personal engineering demonstration", architecture: "Architecture", boundaries: "Intentional boundaries", implementation: "Implementation details, run instructions and supporting artefacts are maintained in the project source folder.", evidence: "Engineering evidence", implementationTitle: "Explore the implementation", read: "Read the project-specific documentation and source structure.", review: "Review the verification approach and local quality gates.", history: "Use the repository history to follow incremental development.", openProject: "Open project on GitHub", notice: "This is a personal demonstration project, separate from professional employment experience. It contains no employer-confidential information, credentials or production data." },
    es: { projects: "Proyectos", source: "Código en GitHub", explore: "Explorar proyecto →", footer: "Demostraciones personales de ingeniería. Son independientes de la experiencia profesional y no contienen información confidencial de empleadores, credenciales ni datos de producción.", heroTitle: "Evidencia de ingeniería, no solo listas de tecnologías.", heroText: "Desarrollo de software orientado a backend, integraciones preparadas para la nube y automatización práctica con el ecosistema Microsoft. Cada proyecto conecta decisiones de arquitectura con código ejecutable, pruebas y activos de despliegue.", exploreProjects: "Explorar proyectos", openRepository: "Abrir repositorio en GitHub", selected: "Trabajo seleccionado", eleven: "Once demostradores especializados", selectedText: "Cada página explica el alcance, la arquitectura, las tecnologías relevantes y la verificación que respalda la implementación.", principles: "Principios de trabajo", professional: "Profesional por diseño", principlesText: "El portfolio prioriza límites claros, comportamiento verificable y evidencia de ingeniería desplegable.", verifiable: "Verificable", verifiableText: "Cada incremento debe compilar, probarse o validarse mediante un control de calidad local adecuado.", security: "Consciente de la seguridad", securityText: "Los proyectos evitan credenciales, datos de producción y supuestos ocultos; los límites de integración son explícitos.", maintainable: "Mantenible", maintainableText: "Documentación legible, alcance enfocado y arquitectura clara hacen que cada demostración sea práctica de explorar.", viewSource: "Ver código y documentación", allProjects: "Todos los proyectos", focus: "Enfoque", verification: "Verificación", scope: "Alcance", personal: "Demostración personal de ingeniería", architecture: "Arquitectura", boundaries: "Límites intencionados", implementation: "Los detalles de implementación, las instrucciones de ejecución y los artefactos de apoyo se mantienen en la carpeta fuente del proyecto.", evidence: "Evidencia de ingeniería", implementationTitle: "Explorar la implementación", read: "Lee la documentación específica y la estructura del código fuente.", review: "Revisa el enfoque de verificación y los controles locales de calidad.", history: "Usa el historial del repositorio para seguir el desarrollo incremental.", openProject: "Abrir proyecto en GitHub", notice: "Este es un proyecto de demostración personal, independiente de la experiencia profesional. No contiene información confidencial de empleadores, credenciales ni datos de producción." }
  };
  const requestedLanguage = new URLSearchParams(window.location.search).get("lang");
  let language = requestedLanguage === "es" || requestedLanguage === "en" ? requestedLanguage : localStorage.getItem("portfolio-language") || (navigator.language.startsWith("es") ? "es" : "en");
  const t = () => copy[language];
  const setLanguage = value => { language = value; localStorage.setItem("portfolio-language", value); document.documentElement.lang = value; render(); };
  const languageSelector = () => `<div class="language-switch" aria-label="Language selector"><button class="${language === "en" ? "active" : ""}" type="button" data-language="en">EN</button><button class="${language === "es" ? "active" : ""}" type="button" data-language="es">ES</button></div>`;
  const header = () => `<header class="shell topbar"><a class="brand" href="${root}/"><img src="${root}/assets/a-sharp-logo.png" alt="A#" />Alex Arceo</a><nav class="nav"><a href="${root}/#projects">${t().projects}</a><a href="${repository}">${t().source}</a></nav>${languageSelector()}</header>`;
  const projectUrl = (project) => `${root}/projects/${project.slug}/`;
  const card = (project) => `<a class="card" href="${projectUrl(project)}"><span class="number">${language === "es" ? "PROYECTO" : "PROJECT"} ${project.number}</span><h3>${escape(project.name)}</h3><p>${escape(language === "es" ? project.focusEs : project.focus)}</p><div class="tags">${project.stack.map(item => `<span class="tag">${escape(item)}</span>`).join("")}</div><span class="card-link">${t().explore}</span></a>`;
  const footer = () => `<footer class="footer"><div class="shell">${t().footer}</div></footer>`;

  const render = () => {
    document.documentElement.lang = language;
    document.title = language === "es" ? "Alex Arceo | Portfolio de ingeniería" : "Alex Arceo | Engineering Portfolio";
    if (!projectSlug) {
      app.innerHTML = `${header()}<section class="shell hero"><div class="hero-copy"><p class="eyebrow">.NET · Azure · AI Automation · Power Platform</p><h1>${t().heroTitle}</h1><p>${t().heroText}</p><div class="actions"><a class="button primary" href="#projects">${t().exploreProjects}</a><a class="button" href="${repository}">${t().openRepository}</a></div></div><img class="portrait" src="${root}/assets/profile_circle.png" alt="Alex Arceo" /></section><section class="shell section" id="projects"><div class="section-head"><div><p class="eyebrow">${t().selected}</p><h2>${t().eleven}</h2></div><p>${t().selectedText}</p></div><div class="project-grid">${projects.map(card).join("")}</div></section><section class="shell section"><div class="section-head"><div><p class="eyebrow">${t().principles}</p><h2>${t().professional}</h2></div><p>${t().principlesText}</p></div><div class="principles"><article class="principle"><h3>${t().verifiable}</h3><p>${t().verifiableText}</p></article><article class="principle"><h3>${t().security}</h3><p>${t().securityText}</p></article><article class="principle"><h3>${t().maintainable}</h3><p>${t().maintainableText}</p></article></div></section>${footer()}`;
      bindLanguageSelector();
      return;
    }

    const project = projects.find(item => item.slug === projectSlug);
    if (!project) { window.location.replace(`${root}/`); return; }
    const projectLogo = project.logo ? `${root}/${project.source}/${project.logo}` : `${root}/assets/a-sharp-logo.png`;
    const sourceUrl = `${repository}/tree/main/${project.source}`;
    const focus = language === "es" ? project.focusEs : project.focus;
    const architecture = language === "es" ? project.architectureEs : project.architecture;
    const evidence = language === "es" ? project.evidenceEs : project.evidence;
    app.innerHTML = `${header()}<section class="shell project-hero"><div><p class="eyebrow">${language === "es" ? "Proyecto" : "Project"} ${project.number}</p><h1>${escape(project.name)}</h1><p class="intro">${escape(focus)}</p><div class="actions"><a class="button primary" href="${sourceUrl}">${t().viewSource}</a><a class="button" href="${root}/#projects">${t().allProjects}</a></div></div><img class="project-mark" src="${projectLogo}" alt="${escape(project.name)} mark" /></section><section class="shell section"><div class="facts"><article class="fact"><strong>${t().focus}</strong><span>${escape(project.stack.join(" · "))}</span></article><article class="fact"><strong>${t().verification}</strong><span>${escape(evidence)}</span></article><article class="fact"><strong>${t().scope}</strong><span>${t().personal}</span></article></div></section><section class="shell section details"><div><p class="eyebrow">${t().architecture}</p><h2>${t().boundaries}</h2><p>${escape(architecture)}</p><p>${t().implementation}</p></div><div><p class="eyebrow">${t().evidence}</p><h2>${t().implementationTitle}</h2><ul><li>${t().read}</li><li>${t().review}</li><li>${t().history}</li></ul><div class="actions"><a class="button primary" href="${sourceUrl}">${t().openProject}</a></div></div></section><section class="shell"><div class="notice">${t().notice}</div></section>${footer()}`;
    bindLanguageSelector();
  };
  const bindLanguageSelector = () => document.querySelectorAll("[data-language]").forEach(button => button.addEventListener("click", () => setLanguage(button.dataset.language)));
  render();
})();
