(() => {
  const repository = "https://github.com/AlexArceoDeveloper/portfolio";
  const projects = [
    { slug: "aspnet-core-api", number: "01", name: "ASP.NET Core API", focus: "A compact API reference implementation with explicit validation and integration tests.", stack: ["C#", "ASP.NET Core", "xUnit"], architecture: "A minimal API boundary keeps input validation, responses and integration behaviour easy to inspect.", evidence: "Release build and xUnit API integration tests", source: "01-aspnet-core-api" },
    { slug: "ai-workflow-integration", number: "02", name: "AI Workflow Integration", focus: "A provider-neutral orchestration service with explicit tool boundaries and safe outputs.", stack: [".NET", "REST APIs", "AI integration"], architecture: "The orchestration layer separates workflow intent from individual model-provider integrations.", evidence: "Release build in CI", source: "02-ai-workflow-integration" },
    { slug: "blazor-delivery-dashboard", number: "03", name: "Blazor Delivery Dashboard", focus: "A delivery-oriented Blazor interface that presents API-backed work clearly.", stack: ["Blazor", "C#", "REST APIs"], architecture: "The UI consumes a defined application boundary and keeps operational status easy to understand.", evidence: "Release build in CI", source: "03-blazor-delivery-dashboard" },
    { slug: "intelligent-commerce-platform", number: "04", name: "Intelligent Commerce Platform", focus: "A modern payments API with persistence, signed webhooks, idempotency and explainable risk rules.", stack: [".NET 10", "EF Core", "PostgreSQL", "Docker"], architecture: "Domain rules, persistence and payment-facing boundaries are kept explicit for safe operational behaviour.", evidence: "Executable domain tests, Compose and Kubernetes validation", source: "04-intelligent-commerce-platform" },
    { slug: "agentic-knowledge-hub", number: "05", name: "Agentic Knowledge Hub", focus: "A grounded retrieval design with approval-aware agents, evaluation and external vector adapters.", stack: ["RAG", "Python", ".NET", "pgvector"], architecture: "Retrieval, evaluation and approval boundaries are independently testable rather than hidden inside a chat interface.", evidence: "Executable Python, safety, workflow and retrieval tests", source: "05-agentic-knowledge-hub" },
    { slug: "commerce-companion", number: "06", name: "Commerce Companion", focus: "A native .NET MAUI client that consumes the commerce API through typed, safe HTTP boundaries.", stack: [".NET MAUI", "C#", "MVVM"], architecture: "Client validation and API communication stay separated from the commerce service itself.", evidence: "Windows release build in CI", source: "06-commerce-companion" },
    { slug: "industrial-telemetry-platform", number: "07", name: "Industrial Telemetry Platform", focus: "A simulated industrial telemetry flow with MQTT ingestion, append-only events and an operations dashboard.", stack: ["MQTT", "Blazor", "C#", "Docker"], architecture: "Telemetry ingestion, persistence and operations visibility are represented as distinct platform responsibilities.", evidence: "Executable rules and persistence tests", source: "07-industrial-telemetry-platform" },
    { slug: "ai-automation-backend", number: "08", name: "AI Automation Backend", focus: "A .NET 10 backend for agents, RAG, identity, observability and a Python neural-routing service.", stack: [".NET 10", "FastAPI", "OpenTelemetry", "PostgreSQL"], architecture: "The API, agent workflow, neural-routing service and operational telemetry are deliberately separated.", evidence: "Executable .NET and Python tests plus Compose topology", source: "08-ai-automation-backend" },
    { slug: "ai-workflow-control-center", number: "09", name: "AI Workflow Control Center", focus: "An ASP.NET Core MVC control centre for explainable routing and approval-aware workflow planning.", stack: ["ASP.NET Core MVC", "Razor", "C#"], architecture: "Strongly typed views make planning decisions and approval requirements visible to operators.", evidence: "Release build and executable planning tests", source: "09-ai-workflow-control-center" },
    { slug: "field-assistant-blazor-hybrid", number: "10", name: "Field Assistant · Blazor Hybrid", focus: "A .NET MAUI Blazor Hybrid client with typed agent integration, HTTPS boundaries and an offline-safe outbox.", stack: [".NET MAUI", "Blazor Hybrid", "C#"], architecture: "Transient authentication, endpoint validation and offline handling are isolated in a reusable client core.", evidence: "Windows release build and executable core tests", source: "10-field-assistant-blazor-hybrid" },
    { slug: "power-platform-service-requests", number: "11", name: "Power Platform Service Requests", focus: "An ALM-friendly request workflow design around Power Apps Canvas, SharePoint, Power Automate and Copilot Studio.", stack: ["Power Apps", "SharePoint", "Power Automate", "Copilot Studio"], architecture: "The Canvas app is the input boundary; SharePoint is the operational record; the flow validates, routes, records history and notifies owners.", evidence: "Offline schema and secret-safety validation", source: "11-power-platform-service-requests", logo: "assets/service-requests-mark.svg" }
  ];

  const root = document.body.dataset.root || ".";
  const app = document.getElementById("app");
  const projectSlug = document.body.dataset.project;
  const escape = (value) => value.replace(/[&<>"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character]);
  const header = () => `<header class="shell topbar"><a class="brand" href="${root}/"><img src="${root}/assets/a-sharp-logo.png" alt="A#" />Alex Arceo</a><nav class="nav"><a href="${root}/#projects">Projects</a><a href="${repository}">Source on GitHub</a></nav></header>`;
  const projectUrl = (project) => `${root}/projects/${project.slug}/`;
  const card = (project) => `<a class="card" href="${projectUrl(project)}"><span class="number">PROJECT ${project.number}</span><h3>${escape(project.name)}</h3><p>${escape(project.focus)}</p><div class="tags">${project.stack.map(item => `<span class="tag">${escape(item)}</span>`).join("")}</div><span class="card-link">Explore project →</span></a>`;
  const footer = () => `<footer class="footer"><div class="shell">Personal engineering demonstrations. They are separate from professional employment experience and contain no employer-confidential information, credentials or production data.</div></footer>`;

  if (!projectSlug) {
    app.innerHTML = `${header()}<section class="shell hero"><div class="hero-copy"><p class="eyebrow">.NET · Azure · AI Automation · Power Platform</p><h1>Engineering evidence, not just technology lists.</h1><p>Backend-focused software development, cloud-ready integrations and practical automation with the Microsoft stack. Each project links architecture decisions to runnable code, tests and deployment assets.</p><div class="actions"><a class="button primary" href="#projects">Explore projects</a><a class="button" href="${repository}">Open GitHub repository</a></div></div><img class="portrait" src="${root}/assets/profile_circle.png" alt="Alex Arceo" /></section><section class="shell section" id="projects"><div class="section-head"><div><p class="eyebrow">Selected work</p><h2>Eleven focused demonstrators</h2></div><p>Each page explains scope, architecture, relevant technology and the verification that supports the implementation.</p></div><div class="project-grid">${projects.map(card).join("")}</div></section><section class="shell section"><div class="section-head"><div><p class="eyebrow">Working principles</p><h2>Professional by design</h2></div><p>The portfolio favours clear boundaries, testable behaviour and deployable engineering evidence.</p></div><div class="principles"><article class="principle"><h3>Verifiable</h3><p>Every increment is expected to build, test or validate through an appropriate local quality gate.</p></article><article class="principle"><h3>Security-aware</h3><p>Projects avoid credentials, production data and hidden assumptions; integration boundaries are made explicit.</p></article><article class="principle"><h3>Maintainable</h3><p>Readable documentation, focused scope and clear architecture make each demonstration practical to explore.</p></article></div></section>${footer()}`;
    return;
  }

  const project = projects.find(item => item.slug === projectSlug);
  if (!project) { window.location.replace(`${root}/`); return; }
  const projectLogo = project.logo ? `${root}/${project.source}/${project.logo}` : `${root}/assets/a-sharp-logo.png`;
  const sourceUrl = `${repository}/tree/main/${project.source}`;
  app.innerHTML = `${header()}<section class="shell project-hero"><div><p class="eyebrow">Project ${project.number}</p><h1>${escape(project.name)}</h1><p class="intro">${escape(project.focus)}</p><div class="actions"><a class="button primary" href="${sourceUrl}">View source and documentation</a><a class="button" href="${root}/#projects">All projects</a></div></div><img class="project-mark" src="${projectLogo}" alt="${escape(project.name)} mark" /></section><section class="shell section"><div class="facts"><article class="fact"><strong>Focus</strong><span>${escape(project.stack.join(" · "))}</span></article><article class="fact"><strong>Verification</strong><span>${escape(project.evidence)}</span></article><article class="fact"><strong>Scope</strong><span>Personal engineering demonstration</span></article></div></section><section class="shell section details"><div><p class="eyebrow">Architecture</p><h2>Intentional boundaries</h2><p>${escape(project.architecture)}</p><p>Implementation details, run instructions and supporting artefacts are maintained in the project source folder.</p></div><div><p class="eyebrow">Engineering evidence</p><h2>Explore the implementation</h2><ul><li>Read the project-specific documentation and source structure.</li><li>Review the verification approach and local quality gates.</li><li>Use the repository history to follow incremental development.</li></ul><div class="actions"><a class="button primary" href="${sourceUrl}">Open project on GitHub</a></div></div></section><section class="shell"><div class="notice">This is a personal demonstration project, separate from professional employment experience. It contains no employer-confidential information, credentials or production data.</div></section>${footer()}`;
})();
